### ISSUE TITLE
example missing ".Strategy"

### ISSUE THREAD

**Issue by ali-joumma** [themikenicholson/passport-jwt#1]
in the example the require statement is written as such var "JwtStrategy = require('passport-jwt')"

i had to add ".Strategy" so it would work

"var JwtStrategy = require('passport-jwt').Strategy"

otherwise it gives me an error
"passport.use(new JwtStrategy('secret', opts, function(jwt_paylaod, done) {
             ^
TypeError: object is not a function
"

**Comment by themikenicholson** [comment]
Thanks for catching this!  My apologies for not getting around to this much sooner.
