### ISSUE TITLE
Expires Date

### ISSUE THREAD

**Issue by 1fabiopereira** [themikenicholson/passport-jwt#107]
How to can I set expires date for the JTW, in the create moment ?

**Comment by themikenicholson** [comment]
That is going to depend on how you are creating the JWT.  This library doesn't create the JWT, only ensure that the JWT is valid.  To create a JWT usually you'll want to use another service or your own endpoint that is authenticated via username/password.  

If you're using the [jsonwebtoken ](https://github.com/auth0/node-jsonwebtoken) module take a look at the `expiresIn` option.

**Comment by max8hine** [comment]
I am not answering this question. I am in doubt about this as well =)

I add `expiresIn` as `exp` property in the JWT payload
but how this lib handle it? it seems does throw any error out

the code below is my way to deal with expiration

``` js
function generateJwtToken(userId) {
	return JWT
		.sign({
			sub: userId,
			iat: Date.now(),
			exp: Date.now() + 1000 // add 1s
		}, JWT_SECRET)
}
// passport middleware
passport.use(new JwtStrategy({
	jwtFromRequest: ExtractJwt.fromHeader('x-auth'),
	secretOrKey: JWT_SECRET,
}, (payload, done) => {
	// =========  Manuly handle ===============
	const isExpired = (payload.exp - Date.now()) < 0
	if (isExpired) return done(new Error('Token Expired'), false)
    // =========================================
	User.model
		.findById(payload.sub)
		.exec()
		.then((user) => {
			if (!user) return Promise.reject(new Error('User_Id is not Found.'))
			done(null, user)
		})
		.catch((error) => {
			done(error.message || new Error(error), false)
		})
}))

```
