### ISSUE TITLE
How to handle a route that authentication is optional?

### ISSUE THREAD

**Issue by zackiles** [themikenicholson/passport-jwt#110]
Coming from express cookie session, if a session is found it will automatically set req.user with a logged in user. I'd like to create routes that authenticates req.user for authenticated users but still allow non authenticated users to access the route. Currently the passport.authenticate('jwt') function will just throw an error if there is no authentication forcing me to create authenticated-only routes. Would anybody be as kind to give me a workaround? Maybe a way to call authenticate not within a route handler?

**Comment by juhaelee** [comment]
@zackiles did you find a solution for this?

**Comment by jeremieca** [comment]
Same problem for me !

**Comment by HRK44** [comment]
Any solution to look at for this?

**Comment by demisx** [comment]
This is what the [passport-anonymous](https://github.com/jaredhanson/passport-anonymous) strategy is for. Just chain it after `JWT` one.

**Comment by VincentJonathan** [comment]
The quick guide on using `passport-anonymous` with `passport-jwt`
1. `npm install passport-anonymous`
2. use the strategy
```js
passport.use(new AnonymousStrategy());
```
3. Add to middleware
```js
router.get("/", passport.authenticate(["jwt", "anonymous"], {session:false}), (req, res) => {
    if (req.user) {
        console.log("User logged in", req.user);
    } else {
        console.log("User isn't logged in");
    }
});
```
Keep in mind that `jwt` should come first, then `anonymous`

**Comment by Brenndoerfer** [comment]
`passport-anonymous` is indeed the right solution.

You can define functions add as middleware on certain routes:
```
module.exports.requiresAuth = passport.authenticate('jwt', {session: false, failureRedirect: '/'});
module.exports.canHaveAuth = passport.authenticate(['jwt', 'anonymous'], {session: false}
```
