### ISSUE TITLE
How to differ wrong and expired tokens

### ISSUE THREAD

**Issue by DzmitryU** [themikenicholson/passport-jwt#119]
Hello everyone!

Now I use following code for authentication:
```node
const jwtOptions = {

    jwtFromRequest: ExtractJwt.fromAuthHeader(),

    secretOrKey: 'jwtSecret'
};

...

passport.use(new JwtStrategy(jwtOptions, (payload, done) => done(null, payload)));

...

passport.authenticate('jwt', { session: false },

    (err, payload) => {

    if (payload) {

         ...

     } else {

        ...

     }

})
```

But for expired and wrong token I get payload=false and err=null.
Does there exist any way to handle this different cases and determine what caused empty payload? (if token was wrong/missing or expired)

**Comment by noinkling** [comment]
Add a third parameter to the `authenticate` callback (e.g. `info`). If verification failed that will contain the error.

See #75 for more info

**Comment by themikenicholson** [comment]
Looks link @noinkling answered the question sufficiently.
