### ISSUE TITLE
TypeError: Cannot read property 'authorization' of undefined

### ISSUE THREAD

**Issue by teckays** [themikenicholson/passport-jwt#120]
Would be nice to do a safe-check at this [line](https://github.com/themikenicholson/passport-jwt/blob/master/lib/extract_jwt.js#L56) `if (request.headers[AUTH_HEADER])` since some requests don't support custom headers (websocket for example) so even though I have an extractor that matches my request, the headers extractor fails because there's no `request.headers` object present.

**Comment by themikenicholson** [comment]
I'm not sure I understand the problem.  The provided extractors are just there to cover common cases, if you have a condition where one of the provided extractors doesn't do what you want it to you can simply write your own.

Are you trying to use multiple extractors together? Some code illustrating how you construct the strategy might help me to understand what you're trying to do.

**Comment by themikenicholson** [comment]
@teckays does writing a custom extractor solve the problem?
