### ISSUE TITLE
Socket.IO authentication

### ISSUE THREAD

**Issue by erreina** [themikenicholson/passport-jwt#121]
Hi, we are currently using passport-jwt for authentication in a project and we needed also to authenticate socket.io connections so I wrote an small middleware [passport-jwt.socketio](https://github.com/erreina/passport-jwt.socketio)  based on passport-jwt. Still is a work in progress but I think users of passport-jwt may be interested. Comments and collaborations are welcome!

Best,
Ernesto

**Comment by themikenicholson** [comment]
Thanks for the info but closing since there is not really anything for me to do.
