### ISSUE TITLE
fromAuthHeader is not a function

### ISSUE THREAD

**Issue by AnimeshKashyap** [themikenicholson/passport-jwt#126]
const JwtStrategy = require('passport-jwt').Strategy;
const ExtractJwt = require('passport-jwt').ExtractJwt;
module.exports = function(passport){
  let opts = {};
  opts.jwtFromRequest = ExtractJwt.fromAuthHeader();
                                   ^

TypeError: ExtractJwt.fromAuthHeader is not a function

**Comment by themikenicholson** [comment]
This was done intentionally.  V3.0.0 was released as a major version precisely because it is not API compatible.  See https://github.com/themikenicholson/passport-jwt#migrating-from-2xx-to-3xx for reasoning and upgrade path.
