### ISSUE TITLE
refresh expired tokens?

### ISSUE THREAD

**Issue by RodrigoAngeloValentini** [themikenicholson/passport-jwt#132]
How I do for refresh a expired token?

**Comment by michie1** [comment]
It's not possible to refresh an expired token. You need to create a new one.

**Comment by pumano** [comment]
It's possible to implement different strategy aka JwtRefreshStrategy with same data as JwtStrategy, but with different name? In JwtStrategy name is 'jwt'. I need also one 'jwt-refresh' name. Can you add please method for set name to strategy?

**Comment by themikenicholson** [comment]
Closing as this is a general question about JWT's with very little to do about the passport-jwt module.  Questions like this are more suited for forums like StackOverflow.
