### ISSUE TITLE
What am I doing wrong

### ISSUE THREAD

**Issue by ThunderRoid** [themikenicholson/passport-jwt#138]
I don't know what happened, but my Passport Jwt Auth is not working.

**in app.js**

    app.use(passport.initialize());

    passport.serializeUser(function (user, done) {
        done(null, user);
    });
    passport.deserializeUser(function (user, done) {
        done(null, user);
    });

    passport.use(new JwtStrategy({
            secretOrKey: jwtSecret,
            jwtFromRequest: JwtExtract.fromAuthHeaderAsBearerToken()
        }, function (payload, done) {
            console.log("Auth : JwtStrategy");
            moduleUser.User.findById(payload._doc._id)
                .exec()
                .then(function (user) {
                        if (user) done(null, user);
                        else done(null, false);
                    }
                )
                .catch(function (err) {
                    return done(err, false);
                });
        }
    ));

NOTE: `console.log("Auth : JwtStrategy");` never gets called

**My Login API**

    router.post('/login', function (req, res) {
        if (req.body.username && req.body.password) {
            moduleUser.User.findOne({username: req.body.username, password: req.body.password})
                .exec()
                .then(function (user) {
                    if (user) {
                        res.json({
                            success: true,
                            message: 'Login successful',
                            token: 'JWT ' + jwt.sign(user.toObject(), jwtSecret, {expiresIn: '14 days'})
                        });
                    } else {
                        res.json({
                            success: false,
                            message: 'Please enter valid login details'
                        });
                    }
                })
        } else {
            res.status(401).json({
                error: 'All information not provided'
            });
        }
    });

**And my Not working Private route**

    router.get('/private', passport.authenticate('jwt', {session: false}),
        function (req, res) {
            res.send('respond with a resource!!!!');
        }
    );
`

**I Always receive 401 as a response**

URL: http://localhost:5000/users/private

Headers-> Authorization: JWT eyJhb......

Am I doing anything wrong here? Any help is appreciated

**Comment by HaiDang666** [comment]
i have same problem, it's seem passport-jwt not recognize the header

**Comment by nexig** [comment]
@ThunderRoid if you use jwtFromRequest: JwtExtract.fromAuthHeaderAsBearerToken() maybe you should set your header like this ->  Authorization: Bearer eyJhb......

**Comment by ThunderRoid** [comment]
@nexig the documentation doesn't say anything about `Authorization: Bearer eyJhb......` 
But I will try it out and let you know. Thank you

**Comment by nexig** [comment]
@ThunderRoid the readmy says:

<img width="991" alt="bearer" src="https://user-images.githubusercontent.com/10259698/33287285-83529ed4-d3b8-11e7-9617-9825c8dff6fb.png">

**Comment by ThunderRoid** [comment]
It works perfectly now, THANKS so much

But why does the Documentation says.....

![image](https://user-images.githubusercontent.com/3328263/33302769-7ea236c4-d3b3-11e7-9214-38b4285e121a.png)

**Comment by HaiDang666** [comment]
'JWT' if no auth schema was specified. Take a look in the function you used which is fromAuthHeaderAsBearerToken() (beaerer schema)

**Comment by themikenicholson** [comment]
Ah, looks like that bit of the README fell out of date.  I will correct this.
