### ISSUE TITLE
Wrapping authenticate method

### ISSUE THREAD

**Issue by kadosh1000** [themikenicholson/passport-jwt#141]
Hi, I am trying to wrap the authenticate method so I can always check for user.
I have tried the following

![image](https://user-images.githubusercontent.com/2615945/34555930-f7202ccc-f13c-11e7-8fda-b5c74aaabdca.png)

But it never gets to the console.log and instead directly responses with 401. Is there a way to prevent it and simply return the callback so I can define the desired action?

**Comment by EddyTheDove** [comment]
Hello, try like this

`app.use((req, res, next) => {
    passport.authenticate('jwt', {session: false}, (err, user, info) => {
        if (!user) {
            console.log('no user found in JWT', info)
        }
        next()
    })(req, res, next) // You must put this;
})`

**Comment by kadosh1000** [comment]
@EddyTheDove 
Thanks I have used it that way pretty much after posting this issue and forgot to comment and close it.

Thanks anyway!
