### ISSUE TITLE
Verify callback not passing info parameter to req

### ISSUE THREAD

**Issue by aaronfulkerson** [themikenicholson/passport-jwt#146]
As you can see in the following Gist, I'm forced to create a custom callback because the info parameter (line 17 of passport.js) isn't being passed to the next middleware's req variable. Isn't the expected behavior for info to be passed to the next middleware as req.info?

https://gist.github.com/aaronfulkerson/4b87f12eabc453ad1958f01e6c46af61

**Comment by themikenicholson** [comment]
Are you sure this is an issue with this passport strategy?  If you look at https://github.com/themikenicholson/passport-jwt/blob/master/lib/strategy.js#L115 you'll see that info is being passed to the success callback by this strategy.  

I don't believe it is the strategies responsibility to set anything on the request object.

**Comment by themikenicholson** [comment]
Closing due to lack of response.
