### ISSUE TITLE
nsp found vulnerability

### ISSUE THREAD

**Issue by oskaryil** [themikenicholson/passport-jwt#147]
node security check just found a new vulnerability in `passport-jwt` which goes down to `jsonwebtoken` > `joi` > `hoek`.
https://nodesecurity.io/advisories/566

![image](https://user-images.githubusercontent.com/16903955/36296883-dd040bea-12ef-11e8-8a01-88e1d1196878.png)

**Comment by daraghking** [comment]
From some quick research the solution to this will be to update to v8 of jsonwebtoken. They dropped the Joi dependency in this major release. I ran the tests on an updated dependency (v8.1.1) and they all pass.

This might be useful: https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v7-to-v8

**Comment by thiagobustamante** [comment]
Any news? It is breaking my build, once nsp is failing

**Comment by thiagobustamante** [comment]
@themikenicholson, Can I send a Pull Request to fix it?

**Comment by themikenicholson** [comment]
Fixed by 4.0.0 release. Closing.

Apologies for taking so long to get to this.
