### ISSUE TITLE
vulnerability found  

### ISSUE THREAD

**Issue by bouyagas** [themikenicholson/passport-jwt#149]
Prototype pollution attack                                                                                                                              
├────────────┼─────────────────────────────────                                                                                 
│ Name       │ hoek                                                               │                                                                                     
├────────────┼────────────────────────────────────────────────────────────────────┤                                                                                     
│ CVSS       │ 4 (Medium)                                                         │                                                                                     
├────────────┼────────────────────────────────────────────────────────────────────┤                                                                                     
│ Installed  │ 2.16.3                                                             │                                                                                     
├────────────┼────────────────────────────────────────────────────────────────────┤                                                                                     
│ Vulnerable │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                       │                                                                                     
├────────────┼────────────────────────────────────────────────────────────────────┤                                                                                     
│ Patched    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                        │                                                                                     
├────────────┼────────────────────────────────────────────────────────────────────┤                                                                                     
│ Path      passport-jwt@3.0.1 > jsonwebtoken@7.4.3 >                                                                                            
      joi@6.10.1 > hoek@2.16.3                                                                                                                          
├────────────┼─────────────────────────────────                                                                                   
│ More Info  │ https://nodesecurity.io/advisories/566                                                                                                        
└────────────┴─────────────────────────────────

**Comment by JulianLaval** [comment]
See #133

**Comment by themikenicholson** [comment]
Closing as duplicate.
