### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by daraghking** [themikenicholson/passport-jwt#151]
@themikenicholson do you intend to actively maintain this module?

**Comment by themikenicholson** [comment]
Yes.  I recently just moved for a new job and have been out of the country for a little while, hence the neglect.  I'll be releasing an update this week to address current issues.

**Comment by daraghking** [comment]
Great news. Congrats on the new job :).

**Comment by themikenicholson** [comment]
Thanks! Update released, closing this issue. Apologies for neglecting the project for so long.
