### ISSUE TITLE
Option to specify other name for `req.user`

### ISSUE THREAD

**Issue by DallasP9124** [themikenicholson/passport-jwt#161]
Currently, successful authorization puts the JSON payload into `req.user`. This is confusing for those who are not associating a user per say with the payload but maybe some other model naming convention of theirs. It would be a nice option to have an option that would specify the name in `req` object other than `user`, like `account` or `signer`, etc.

**Comment by themikenicholson** [comment]
https://github.com/jaredhanson/passport/blob/master/lib/authenticator.js#L117

This is a configuration option of passport and not up to individual strategies to implement.  See the document for [passportjs](http://www.passportjs.org/docs/).
