### ISSUE TITLE
if no auth_token anywhere - stack dump

### ISSUE THREAD

**Issue by cuteboi** [themikenicholson/passport-jwt#17]
TypeError: Cannot read property 'auth_token' of null
      at JwtStrategy.authenticate(<mypath>/node_modules/passport-jwt/lib/strategy.js:97:47)

This is at line 97:47
```javascript
        token = url.parse(req.url, true).query[self._tokenQueryParameterName];
```

**Comment by cuteboi** [comment]
if (!token) {
      var parsed_url =url.parse(req.url, true);
      if(parsed_url.query && parsed_url.query.hasOwnProperty(self._tokenQueryParameterName))
      {
        token = parsed_url.query[self._tokenQueryParameterName];
      }
    }

was my fix to allow the execution to continue.

**Comment by themikenicholson** [comment]
I spent some time trying to reproduce this in a real environment and I am having some difficulty. 

The TypeError only occurs when when req.url is an instance of url.Url and not when req.url is a string.  Running this under node's http.Server always results in  req.url being set to a string.

What http server or framework are you running this under that causes req.url to not be set to a string?

**Comment by cuteboi** [comment]
I tested using postman against a koa, nodejs, koa-passport, passport-jwt.  If you need more, let me know.

```javascript
      console.log("REQ URL", this.req.url);
      var url = require('url');

      var parsed_url = url.parse(this.req.url,true);

      console.log("parsed url", parsed_url);

      console.log("query", parsed_url.query);
```

output:

```
REQ URL /devices/92760
parsed url { protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '',
  query: {},
  pathname: '/devices/92760',
  path: '/devices/92760',
  href: '/devices/92760' }
query {}
```


Here is one with ?something=true

```
REQ URL /devices/92760?something=true
parsed url { protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '?something=true',
  query: { something: 'true' },
  pathname: '/devices/92760',
  path: '/devices/92760?something=true',
  href: '/devices/92760?something=true' }
query { something: 'true' }
```

The problem was that the since the URL has no query with an auth token, it would fail that check, and throw a TypeError, it expected a query property of self._tokenQueryParameterName

When I am not authenticated, and haven't gotten a token anywhere, I should be rejected with "not authenticated" not a "500 error" because the request failed to even complete.

**Comment by cuteboi** [comment]
Hmm, looking over this, and trying to prove myself right some more, I see what you mean.  Is the req not the same as this.req in koa?  I'll dive deeper, and remove my authentication on my app that I'm actively working on.  Give me an hour or so.

**Comment by cuteboi** [comment]
closing

**Comment by themikenicholson** [comment]
No need to feel bad/dumb.  I appreciate the contribution and I'm going to go ahead and merge anyways since I should have been checking that the attribute was present before attempting to access it.
