### ISSUE TITLE
Passport JWT Strategy extracting options

### ISSUE THREAD

**Issue by m-salamon** [themikenicholson/passport-jwt#172]
I would like to use 2 extraction methods for various types of requests.  

Something like this: 
(it does not work)
```
const options = {};
options.jwtFromRequest = ExtractJWT.fromUrlQueryParameter('secret_token')! = undefined ?ExtractJWT.fromUrlQueryParameter('secret_token') : ExtractJWT.fromHeader('secret_token');
options.secretOrKey = process.env.AUTH_SECRET;
```

**Comment by DanielSwiegersServian** [comment]
jwtFromRequest accepts a function.  You could write a custom function to do this.

You could do something like
```
const myFunction = (req) => {
  const urlQueryParam = ExtractJWT.fromUrlQueryParameter('secret_token')(req);
  return urlQueryParam != undefined
    ? urlQueryParam 
    : ExtractJWT.fromHeader('secret_token')(req);
};
options.jwtFromRequest = myFunction;
```

**Comment by themikenicholson** [comment]
@DanielSwiegersServian is right: A custom extractor function is the way to do this.   If you want to contribute a composite extractor that accepts a list of extractors and runs them in order until one returns a valid JWT, please feel free to do so.  Be sure to include unit tests!
