### ISSUE TITLE
Question: How would you go about login in a SPA?

### ISSUE THREAD

**Issue by johannesjo** [themikenicholson/passport-jwt#33]
I'm wondering how to create and deliver the token, when you want to login you're user from a SPA using a password and a username. Would be really cool, if you could provide an example for that too.

**Comment by m-vdb** [comment]
Trying to do the same thing here, I'm thinking about doing it and use an `/authenticate` route that takes a POST with (username, password) and then returns the token, to be used in next requests

**Comment by johannesjo** [comment]
I ended up doing something like this:
http://stackoverflow.com/questions/33357799/how-to-do-authentication-for-an-api-build-with-express

**Comment by m-vdb** [comment]
makes sense

**Comment by themikenicholson** [comment]
Another good tutorial I came across was this: https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens#authenticating-and-creating-a-token

It doesn't use passport-jwt but it should be fairly easy to see what bits of the tutorial can be replaced with it.

I'm going to go ahead and close this but feel free to re-open if you still have questions.
