### ISSUE TITLE
Generation of the token

### ISSUE THREAD

**Issue by sylvainlap** [themikenicholson/passport-jwt#34]
Is this lib responsible for the jwt generation (during the auth process), or is it only responsible for checking a token ?

**Comment by themikenicholson** [comment]
No, this library is not responsible for the generation of the token.

I originally wrote the library to validate tokens created by Android's authentication api.

If you want a tutorial that explains how to create your own tokens you can check out https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens#authenticating-and-creating-a-token

**Comment by themikenicholson** [comment]
I'm going to go ahead and close this but feel free to re-open if I didn't answer your question.
