### ISSUE TITLE
Missing request parameter in JwtStrategy verify function documentation

### ISSUE THREAD

**Issue by mstueve** [themikenicholson/passport-jwt#35]
When first implementing the sample code I was getting an error that 'jwt_payload.sub' was undefined. Looking a little closer I discovered that the verify function takes 3 args - the request, the payload, and callback. So:

`passport.use(new JwtStrategy(opts, function(jwt_payload, done) {`

Should be

`passport.use(new JwtStrategy(opts, function(req, jwt_payload, done) {`

**Comment by roxeteer** [comment]
You need to `opts.passReqToCallback` to `true` to get the request as a parameter. Otherwise the callback will receive only payload and done.

**Comment by iamsebastian** [comment]
True. This can be closed.

**Comment by Shahidedy** [comment]
this is the code i am using and when i do console.log(jwt_payload.sub), it always says "undefined" and fetches the first record from DB. Can somebody please help?
var JwtStrategy = require('passport-jwt').Strategy,
    ExtractJwt = require('passport-jwt').ExtractJwt;
var passport = require('passport');
var User = require('../models/user');
var config = require('../config/main');


// Setup work and export for the JWT passport strategy
module.exports = function(passport) {
  var opts = {}
  opts.jwtFromRequest = ExtractJwt.fromAuthHeader();
  opts.secretOrKey = config.secret;

  opts.passReqToCallback = true;
  //opts.issuer = "accounts.examplesoft.com";
  //opts.audience = "yoursite.net";
  passport.use(new JwtStrategy(opts, function(req, jwt_payload, done) {
    console.log(jwt_payload.sub);
   // console.log(req);
    User.findOne({id: jwt_payload.sub}, function(err, user) {
      if (err) {
        return done(err, false);
      }
      if (user) {
        done(null, user);
      } else {
        done(null, false);
        // or you could create a new account
      }
    });
  }));
};

**Comment by devendra1102** [comment]
The passport.use() will automatically run when you call the passport.authenticate('jwt', cb). You should pass the authorization in header with valid JWT signed(`user`) token. If it valid and non-expired token then `payload.sub `will have `user` otherwise it doesnt contain user.

**Comment by Shahidedy** [comment]
Fixed it. 
Thanks for your help @devendra1102

**Comment by oyedotunsodiq045** [comment]
show us d code at shaqhisedy

**Comment by GayathriMohan** [comment]
Is there any way by which I could also get the server response in the JWTStrategy?
