### ISSUE TITLE
handle missing token and expired tokens in the custom function

### ISSUE THREAD

**Issue by episodeyang** [themikenicholson/passport-jwt#41]
Hi,

I'm using `passport-jwt` to authenticate some endpoints that accept request both with and without a jwt token in the header. 

Right now it looks like `passport-jwt` handles this by returning a `401` status code when there is no header/authorization in payload. 

Would it be possible to handle such logic inside the custom function?

I was originally using my own middleware to handle this, but I couldn't figure out how to modify the `req.user` object without express complaining about having  only a getter on `req.user`.

Ge

**Comment by episodeyang** [comment]
Hi, 

I just forked this repo and got it to work.

In my fork, I defer all error handling to the `self._verify` function so that users can handle 
- missing authentication token
- invalid tokens with `jwt_error`s by themselves.

These lead to a change in the contract of the `self._verify` function, which becomes:
```javascript
function (req, jwt_error, jwt_token, authorize)
or 
function (jwt_error, jwt_token, authorize)
```

also, I want to allow the `authorize` call back to **not** throw an error when the user is missing, because my next middlewares uses the `req.user` object when it exists, but it is not required.

If you are interested in these I can fix the tests and submit a PR. If not, it's okay.

Thanks for this module!

**Comment by darth-cheney** [comment]
I have to second what @episodeyang is talking about here. Right now, the strategy obfuscates errors that come built in with `jsonwebtoken`, upon which the strategy is based. Those implementing this strategy cannot send errors that are present in the `jsonwebtoken` module nor can they even inspect them.
  
The verify callback should absolutely include any errors that occurred underneath.

**Comment by vmehera123** [comment]
pls help. got 401 Unauthorized, when trying get secure /api. 

APP.JS
```
opts.secretOrKey = app.get("superSecret");

passport.use(new JwtStrategy(opts, function (jwt_payload, done) {
  User.findOne({email: jwt_payload.email}, function(err, user) {
    if (err) {
      return done(err, false);
    }
    if (user) {
      done(null, user);
    } else {
      done(null, false);
      // or you could create a new account
    }
  });
}));
app.use(passport.initialize());
app.use("/api", passport.authenticate("jwt", {session: false}));
```
/API/LOGIN that generate token

function loginHandler(req, res, next) {
  User.findOne({email: req.body.email}, function (err, user) {
    return res.json({
      token: jwt.sign({email: user.email}, req.app.get("superSecret"), {expiresIn: 120})
    });
}

so, my REQ.HEADERS: 
{
authorization: "token12312j3jkbskjfskjfbsjkdfnksjdnf"
}

what i'm missing? why i'm got 401 Unauthorized if there are token in req.headers?

**Comment by rajaraodv** [comment]
+1

**Comment by olee** [comment]
I used the following middleware to handle at least the situation when mixed authorized and unauthorized access is desired.

````typescript
    app.use((req, res, next) => {
        passport.authenticate('jwt', { session: false }, (error, user, info, status) => {
            if (user === false && info && info.message === 'No auth token') {
				// Just unauthorized - nothing serious, so continue normally
            	return next();
			}
			return unauthenticatedError(res);
        })(req, res, next);
    });
````

**Comment by thaiat** [comment]
+1

**Comment by rdguarcas** [comment]
var token = jwt.sign({ user: User.id }, config.secret,{
								expiresIn:  (1*60),
								algorithm: 'HS256'
							});

res.json({success: true, APIToken: "JWT " + token});

send request Header  :  JWT TOKEN_GENERATE

**Comment by themikenicholson** [comment]
I know this is an old issue, I think what you are looking for is the custom callback feature of passport.  That is where you handle failed authentication, JWT parse errors, etc. See http://passportjs.org/docs#custom-callback

Your custom callback would have the signature: 

```javascript
function (err, user, info) { .... }
```

If a JWT parse error occurs or the JWT is not valid the user will be false and info will contain the error that `jsonwebtoken` provides explaining why validation of the JWT failed.
