### ISSUE TITLE
Need Example

### ISSUE THREAD

**Issue by jbeckton** [themikenicholson/passport-jwt#42]
So when a user logs in how to I generate the JWT token to send back to the client which is attached to future requests?

**Comment by timqian** [comment]
+1 for this

**Comment by jbeckton** [comment]
Answered my own question.

take a look at 

https://github.com/auth0/node-jsonwebtoken

**Comment by themikenicholson** [comment]
Glad you figured it out.  This strategy was only intended to authenticate JWTs, not issue them. I was originally using it with JWT's from a 3rd party and not issued by my own application.

I suppose this behavior could be added to the strategy but the intent was to leave it up to another party like an OAuth2 service.

**Comment by sibeliusseraphini** [comment]
@themikenicholson thanks for this package.

But I think it is a good ideia to also provide a Strategy to issue JWT tokens in this own package

**Comment by themikenicholson** [comment]
@sibeliusseraphini I see where you're coming from but this library was originally designed to work with tokens issued by a 3rd party - particularly those issued by the Google Sign-in API for android.  My primary use case was not to replace easier-to-implement session based auth methods with a JWT. Instead I'm trying to simplify interacting with third parties' oauth2.0 and simliar services using JWT as the token type.

Other JWT authentication strategies also leave issuing the token up to 3rd parties or other modules. See https://www.npmjs.com/package/passport-http-jwt-bearer.

**Comment by sibeliusseraphini** [comment]
I would like to share my solution using koa@2, I need to share the secret to use in jwt and passport-jwt.

This can be used with any Strategy, and will return a json with the JWT token

```js
export function doLogin(ctx, next) {
  return passport.authenticate('custom', async (user, info, status) => {
    if (user === false) {
      ctx.status = 401;
    } else {
      const token = jwt.sign({ id: user._id}, config.secret);
      ctx.body = {
        token: token,
      };
      next();
    }
  })(ctx, next);
}
```

@themikenicholson thanks
