### ISSUE TITLE
Create example

### ISSUE THREAD

**Issue by FREEZX** [themikenicholson/passport-jwt#5]
An example app is needed to fully demonstrate how this works, and includes JWT generation in the code.

**Comment by themikenicholson** [comment]
Hey, Sorry I wasn't able to get to this sooner.  Any particular reason for closing the issue? No longer interested in an example?

**Comment by FREEZX** [comment]
I created my own strategy that takes care of authorization in the middleware, so you can rely on using the req.isAuthenticated function in the code. If you're interested, check out my repo:

**Comment by FREEZX** [comment]
https://github.com/FREEZX/passport-jwt-strategy
