### ISSUE TITLE
Login error: No auth token

### ISSUE THREAD

**Issue by mrpotato3** [themikenicholson/passport-jwt#51]
Hi!

I got the error "No auth token" when I try to authenticate the user. I followed the instructions that appear in this web but I can not dismiss the error. I don't know what's the problem exactly.

With 'local' strategy workflow is ok and scripts executes 'passport.use' function. But with 'jwt' strategy I think when script creates 'new JwtStrategy' and tries to extract auth from header can't do it and shows the error inside 'passport.autheticate'.

There are any error?

**Comment by themikenicholson** [comment]
Can you provide some example code and perhaps a curl command that illustrates how you are passing the token to the to the strategy?

**Comment by mrpotato3** [comment]
Solved.

The error was application prepends "Bearer" in JWT token and paassport-jwt was expecting "JWT".

Thanks.
