### ISSUE TITLE
Using social strategies with sessionless jwt strategy

### ISSUE THREAD

**Issue by edulis8** [themikenicholson/passport-jwt#55]
Hi,
I would be greatly helped and appreciative if there were an available example of how to implement jwt and social (in my case, instagram) strategies in a sessionless approach, for an app where routing is being handled by the frontend.

Thanks!

**Comment by gabosdk** [comment]
https://github.com/jaredhanson/passport-instagram

**Comment by angelxmoreno** [comment]
Is this still needed? I am working on an API that does the initial authentication ( log in ) via Github then passes the JWT token to the front-end. On subsequent requests to the api, the front-end passes the JWT to authenticate the user.

**Comment by edulis8** [comment]
Absolutely a needed thing, I'm done working on my project (sent the JWT to the client-side via query string in the callback url after Instagram authentication, kind of an ugly hack)...

**Comment by angelxmoreno** [comment]
This can be tricky since a good example would include the backend and a frontend. I currently use AngularJS 1.x as a frontend with the [ng-token-auth module](https://github.com/lynndylanhurley/ng-token-auth). If those requirements are to your satisfaction, I could put something together.

**Comment by TD-Stanley** [comment]
I'd be interested to see someone's take on this. I've seen various piecemeal articles online.

**Comment by angelxmoreno** [comment]
I'll slap something together tonight. 
Backend: Express, Sequelize, Passport
Frontend: Angular, NG-Token-Auth

**Comment by Kannaj** [comment]
@angelxmoreno - did you manage to figure it out? i'm trying to do something similar for a react app

**Comment by akshath4u** [comment]
I need the same sample which fulfils below requirement.

I am using express typescript along with routing-controller module. I have to implement jwt and some of social auth using passport. Is there any samples which handle both email password/ social using passport-jwt authentication ? How can i implement this ? Its really confusing.

**Comment by Kannaj** [comment]
I just ended up hijacking githubStrategy and created jwt for each user through oAuth .

https://github.com/Kannaj/42EXP/blob/master/server/passport/passport_github.js#L31

**Comment by themikenicholson** [comment]
Closing as this is out of scope of this module.

There have been several answers with examples of social login strategies. 

@akshath4u There is a good jist in which the author of the passport framework provides his suggestion on how to handle multiple authentication strategies in the same applicaiton: https://gist.github.com/joshbirk/1732068
