### ISSUE TITLE
Add ability to prepend the header string to the token, before trying to decode it

### ISSUE THREAD

**Issue by manuel-di-iorio** [themikenicholson/passport-jwt#58]
I want to send to the client only the JWT token without the header with the algo informations.
To do this, there should be a passport-jwt option to specify a string that will be prepended to the token, before its decodification.

**Example:**
The client sends to the server the request with this header:
`Authorization: JWT eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ`

You may notice that the "header." is missing. passport-jwt, after detected the jwt in the header, will prepend the string "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9." before trying to decode it, to have the final token: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ`

**Comment by themikenicholson** [comment]
Is this a common practice?  What is driving this need? In my experience with using JWTs for authentication the JWT is provided in whole by the party being authenticated. Modifying the JWT as part of authentication seems odd.

I would suggest that you modify the partial JWT from the request before invoking this authentication module. The modified JWT can be added to the request object and you can use a custom extractor function to retrieve it and authenticate it with this module.

**Comment by manuel-di-iorio** [comment]
The use case is to make slightly hard for an user to understand how the token is built (which sign algorithm). Not really odd, or yes?

> I would suggest that you modify the partial JWT from the request

It looks like a good choice, so before invoking `passport.authenticate('jwt', etc..`

For anyone else:

```javascript
if (req.headers.authorization)
    req.headers.authorization = "JWT " + header + req.headers.authorization;

passport.authenticate('jwt', etc...
```

Of course, after have modified  how the client sends the token in the header

**Comment by manuel-di-iorio** [comment]
@themikenicholson As you can see, a unified way for every extractor would be better
