### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by mikecann** [themikenicholson/passport-jwt#60]
Hi,

I have been looking at JWT in my app. I like the look of passport and your library but I think I may be missing some concepts such as how to generate the JWT and how exactly the jwt_payload is populated.

I think what would be super helpful for me and perhaps others would be an end-to-end example from username / password login to getting the token then using that to get some protected api data.

Do you think this would be possible?

Cheers
Mike

**Comment by justspamjustin** [comment]
+1 Do you recommend using another library to generate the token such as [node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken). Would you use passport-local to do the initial authentication with the user email and password?

**Comment by stephan-nordnes-eriksen** [comment]
An example of how to use this library would be much appreciated. I too would like to use a simple passport-local signup/login system and add a jwt api to my site, but I am confused as to how to wire everything together.

**Comment by bettercallme** [comment]
This might help you - [](https://www.youtube.com/watch?v=f4F0brwbYKg)

**Comment by bettercallme** [comment]
[This might help you](https://www.youtube.com/watch?v=f4F0brwbYKg)

**Comment by themikenicholson** [comment]
[This tutorial](http://jonathanmh.com/express-passport-json-web-token-jwt-authentication-beginners/) is a good place to start.

I don't know the author but glancing through the code example it seems to cover all of the basics.
