### ISSUE TITLE
fromUrlQueryParameter gives TypeError: parsed_url.query.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by vittau** [themikenicholson/passport-jwt#62]
When using the extractor `fromUrlQueryParameter`, I get the error _TypeError: parsed_url.query.hasOwnProperty is not a function_, which probably has to do with [this](https://github.com/prerender/prerender-node/pull/103).

**Comment by michaelhunziker** [comment]
Same issue here for Node version 6.0.0.

**Comment by emilong** [comment]
ICYMI, @Page- has a fix for this here: https://github.com/themikenicholson/passport-jwt/pull/59

**Comment by infloop** [comment]
The same issue for Node version 6.1.0.

**Comment by themikenicholson** [comment]
#59 was merged.  2.1.0 will be released shortly

**Comment by heartyb** [comment]
Same issue here for Node version 6.9.1.
