### ISSUE TITLE
Destroy current jwt when user logout

### ISSUE THREAD

**Issue by haidnvnn18** [themikenicholson/passport-jwt#64]
How can I destroy current jwt on server when user logout?

**Comment by thedewpoint** [comment]
There's no way to delete it on the server unless you're storing it on the
server. I think the typical way to 'destory' a jwt so that it may not be
reused is to blacklist it in your db.

**Comment by haidnvnn18** [comment]
Ah ok, I see. And only one more small question. I think jwt token will not be generate a same value, is it true?

Eg: 
- day A: gen token has value is X
- day D: gen token has value is X, too.

Any case of this problem occur?

**Comment by themikenicholson** [comment]
Regarding different values of JWT: The value of the JWT is determined by its contents and the keys used to sign the JWT.  If the contents and signing keys are identical each time the JWT is created then the JWT value should not change.  If the JWT includes different any unique content (i.e. a timestamp) than it will have a different value each time the JWT is issued.

With regard to destroying a JWT - jwt's often expire or you can include some unique data, i.e. a session ID that can be verified in the database.

**Comment by themikenicholson** [comment]
Closing, feel free to reopen if you have further questions.
