### ISSUE TITLE
Custom extractor function limitations

### ISSUE THREAD

**Issue by marcandrews** [themikenicholson/passport-jwt#65]
Is it me or is the custom extractor function extremely limited. In my authorization flow, when users sign in, they are issued a new token. When users sign out, their token is stored in a Redis database. Then, if someone tries to use that token again, I can invalidate it by comparing it against the database.

I am trying to accomplish the step of invalidating tokens with the custom extractor function; however, everytime I try to write a _complex_ procedure within it using callbacks or promises, it can never authenticate.

For example, here is the callback version of my extractor function and authorization strategy:

```
function myTokenExtractor(req) {
  return token.verify(req, (err, token) => {
    return token;
  });
}

passport.use('jwt', new jwtStrategy({
  session: false,
  jwtFromRequest: myTokenExtractor,
  secretOrKey: globals.secret
}, function(jwt_payload, done) {
  User.findOne({ _id: jwt_payload.id }, function(err, user) {
    if (user) { return done(null, user); }
    if (err)  { return done(err, null); }
    return done(null, null);
  });
}));
```

It seems like `myTokenExtractor` is running (`console` works within it), but the return is evaluated before token can actually be returned, thus `function(jwt_payload, done)` never runs.

The same thing happens if I structure the extractor function as a `Promise`; `function(jwt_payload, done)` receives the pending promise and not the actual token.

Am I doing something wrong? Does anyone have any ideas on how I can include callbacks/promises in the extractor function?

Note: `extractJwt.fromAuthHeader()` works as expected.

**Comment by themikenicholson** [comment]
The extractor function is not designed to function asynchronously.  It should be a function that takes a request object and immediately returns the JWT that was present in that request.  It is not designed to do any additional processing, database checking, etc. 

The verification you are attempting in the extractor function belongs in the verify callback which *is* designed to work asynchronously.

**Comment by thalalhassan** [comment]
https://stackoverflow.com/a/46942501/12650528 . This might be helpful.
