### ISSUE TITLE
Token parsing is not consistent between ExtractJwt.fromHeader and the default token parser

### ISSUE THREAD

**Issue by jraut** [themikenicholson/passport-jwt#72]
ExtractJwt.fromHeader and the default token parser are inconsistent in functionality.

The default token parser accepts tokens in this form:
```
Authorization: JWT JSON_WEB_TOKEN_STRING.....
```

fromHeader, however, does not work with the previous form. Instead it requires the following: 
```
Authorization: JSON_WEB_TOKEN_STRING.....
```

I wish this was mentioned in the documentation. Consistent implementation would be even better. Thanks for the library in any case!

**Comment by themikenicholson** [comment]
There are multiple extractors that read the JWT from headers, you may just be missing the differences.

**extractors.fromHeader**  reads the JWT from any header, allowing you to specify the header name.

**extractors.fromAuthHeader** works just like the default token parser and reads the JWT from the authorization header if and only if the authentication scheme is 'JWT'

**extractors.fromAuthHeaderWithScheme** reads the JWT from the Authorization header and allows the user to specify the scheme they expect so they can use something different from JWT. 

Each of these extractors was added in response to multiple feature requests.  I don't think its a matter of inconsistent implementation as much as it is enabling as much flexibility as possible.

**Comment by themikenicholson** [comment]
Closing but if you want to suggest some documentation improvements feel free to submit a pull request.

**Comment by jraut** [comment]
`extractors.fromHeader('Authorization')` should be interchangeable with `extractors.fromAuthHeader()`. This is not the case.

The bug responsible for the inconsistency is due to the fact that fromHeader() does not account for the four first characters in `JWT ${token}` as fromAuthHeader() does.
