### ISSUE TITLE
bcrypt + jwt

### ISSUE THREAD

**Issue by CodersBrothers** [themikenicholson/passport-jwt#73]
- JWT, for security, it needs a "Secret Hash".
- bcrypt library, in passwords management, is used for avoid add a salt, because this is insecure and an atacker if have the code have more posibilities to decrypt the passwords.

So, it is posible use bcrypt to avoid the secret hash in jwt protocol, in order to inprove the security?

**Comment by themikenicholson** [comment]
This would be non-standard usage of the JWT.  I'm not a security/crypto guy so I'm sticking with the algorithms suggested in [RFC 7519](https://tools.ietf.org/html/rfc7519). 

Additionally, this library uses the package [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) to perform verification of JWT and therefore only supports the signing algorithms implemented by that library.  If you wish to inject your own verification function you can do so by setting JwtStrategy.JwtVerifier to a new value in lib/strategy.js.
