### ISSUE TITLE
difficulty with default example

### ISSUE THREAD

**Issue by skaplun** [themikenicholson/passport-jwt#74]
Hey Guys,
Tried working with default example but there are no errors passed.

I'm using passport-local to signup users - signup & login goes fine, token is sent to client in electron browser and manually sent back in Authorization header but then nothing happens.
In the route I see correct header, but jwt strategy doesn't start. 
Can you please explain why this is happening?

Jwt route:

```
 router.get('/login/check', function(req, res, next) {
        console.log(JSON.stringify(req.headers));
        passport.authenticate('jwt', { session: false }, function(err, user, info) {
            console.log(err)
            res.json({'success' : true});
        })
    })
```

JWT strategy

```
var JwtStrategy = require('passport-jwt').Strategy,
    ExtractJwt = require('passport-jwt').ExtractJwt;
    var opts = {}
    opts.secretOrKey = 'secret';
    opts.issuer = "http://localhost:3000";
    opts.audience = "http://localhost:3000";
    opts.jwtFromRequest = function(req, res){
        console.log('in custom')
        var token = req.get('Authorization').split(' ');
        console.log(token)
        return token


    }


    passport.use(new JwtStrategy(opts, function(jwt_payload, done) { 
        console.log(1)
        return User
            .findOne({where : {username : jwt_payload.email } })
            .then(function (user) {
                if(user === null){
                    return TempUser
                            .findOne({where : {username : jwt_payload.email } })
                            .then(function(user){
                                return user === null ? 
                                    done(null, false, 'login error, please try again') :
                                    done(null, false, 'email verification needed');
                            });
                } else {
                    if (bcrypt.compareSync(password, user.dataValues.password)){        
                            done(null, user); 
                    } else {
                        done(null, false, 'login error, please try again');
                    }

            }
        });
```

**Comment by devendra1102** [comment]
Where are you writing passport.authenticate(), can you show me?

**Comment by jagged3dge** [comment]
I've hit this one too. Same as the OP, I'm calling `passport.authenticate('jwt')` manually in a route handler.

```js
app.post('/login/validate', function (req, res, next) {
  if (req.headers.authorization) {
    passport.authenticate('jwt', { session: false }, function (err, user, info) {
      if (err) return res.fail(err)
      if (!user) return res.fail(new errors.UserNotFoundError())
      req.user = user
      next()
    })
  }
```

I've tried putting a dummy log statement inside `JwtStrategy.prototype.authenticate` function in source. Doesn't seem to trigger at all. Something fishy going on. The codepath seems simpel enough. Logging the PassportJS instance does show `jwt` under `_strategies`, so it's registered with Passport just fine. I'm on my wits end on this one.

**Comment by themikenicholson** [comment]
@jagged3dge  How are you constructing the strategy?

**Comment by themikenicholson** [comment]
@skaplun Your opt.jwtFromRequest value is wrong.  That function should have the signature `function(req) { ... }` and not `function(req, res) { ... }`.  

I'm guessing that is causing an exception in [here](https://github.com/themikenicholson/passport-jwt/blob/master/lib/strategy.js#L84) when attempting to retrieve the JWT from the request.

**Comment by themikenicholson** [comment]
marking as a question, I've been incorrectly using the help wanted label.

**Comment by themikenicholson** [comment]
Haven't heard anything in some time.  Closing.
