### ISSUE TITLE
Old token still valid after creating new token for the same user

### ISSUE THREAD

**Issue by raj-adroit** [themikenicholson/passport-jwt#76]
Hope it should expiry previous token of the user if he created new one. But its not doing it, I hit login and created n number of jwt token for same user...

All these generated jwt tokens are generated for same user id, when i validate those token with passport-jwt all returns valid..

**I hope it should have only one jwt active for one user at a time, When we generate another token for the same user, it should invalidate previous token**

Am using [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) to generate jwt token, Am able to verify it successfully with passport-jwt

**Comment by dotboris** [comment]
That's normal with JWT. 

The only thing that validates that a JWT is the signature (plus the some of the checks like expiration). There's no built-in way of invalidating tokens. 

You can keep track of a list of invalid tokens or store the current valid token, but that goes against the point of JWT.

**Comment by themikenicholson** [comment]
Marking as help wanted and closing as I think the question was answered well.  Thank you, @dotboris!
