### ISSUE TITLE
401 unauthorized - custom callback

### ISSUE THREAD

**Issue by studio404pl** [themikenicholson/passport-jwt#78]
Hi, plugin works well, thanks for your strategy!

If there is any possibility to callback some action on token revoke? I want to compare it against refresh token and allow to recreate access token instead of throwing 401.

If not, could you let me know where should i start looking for modifying your strategy to fit my needs?

Thanks.

**Comment by themikenicholson** [comment]
I think you're looking for the [Custom Callback](http://passportjs.org/docs#custom-callback) functionality of the Passport module.

The strategy only validates the JWT, passport provides that ability to take custom actions based on the results of the strategies validation.  

Hopefully this helps.

**Comment by themikenicholson** [comment]
Closing for now, if I'm missing something and you think the module doesn't give enough information about the reason for the failure for you to take the necessary steps in a custom callback let me know and we can revisit this.
