### ISSUE TITLE
jwt_payload.sub is undefined

### ISSUE THREAD

**Issue by Shahidedy** [themikenicholson/passport-jwt#80]
findOne always returns first record from my DB. When i print jwt_payload.sub in console, it sayd jwt_payload.sub is undefined. can somebody help understanding this?

**Comment by zombiQWERTY** [comment]
Some issue too. `jwtPayload`from example is smth like this:
`{ iat: 1475587832 }`

**Comment by Shahidedy** [comment]
Fixed it.
Thanks for your comment @zombiQWERTY
