### ISSUE TITLE
set expiration time

### ISSUE THREAD

**Issue by decooliveira** [themikenicholson/passport-jwt#82]
Is there a way to set expiring time when generating a token ?
I realized we could ignore expiration but I couldn't find a way to set that expiration.

**Comment by themikenicholson** [comment]
There is no token generation functionality in this library.  It relies on [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) to perform validation. That library also provides the ability to sign (generate) tokens. 

If you read the documentation for that library you'll see that when signing a token you can supply the expiresIn parameter to control expiration.

**Comment by themikenicholson** [comment]
Marking as closed. Invalid label only because this library does not provide any of JWT generation functionality.
