### ISSUE TITLE
Authorize without jwt

### ISSUE THREAD

**Issue by woutr** [themikenicholson/passport-jwt#93]
I'm trying to use passport-jwt in conjunction with other strategies (eg. Facebook, Twitter).

My current api endpoints look like this:
```
router.get('/', passport.authenticate('jwt', { session: false }), (req, res, next) => {
	passport.authorize('facebook', { state: req.query.state, scope: config.get('facebook.scope') || [] })(req, res, next);
});
```
Essentially, I first authenticate the user through their JWT, then authorize their Facebook account. This all works perfectly, but I also want users to be able to login through their Facebook account.

So when a user makes a request to that endpoint, I want to check if `req.user` is set or not.
According to the [passportjs documentation](http://passportjs.org/docs/authorize) you would use `authorize` instead of `authenticate`. But it seems that passport-jwt always returns unauthrized when no jwt was found.

Is there any way around this? Or should I look for another solution somehow?

**Comment by noinkling** [comment]
The [custom callback form of `authenticate`](http://passportjs.org/docs/#custom-callback) is available for when you want to customize success/failure behaviour:

```js
router.get('/', (req, res, next) => {
  passport.authenticate('jwt', { session: false }, (err, user, info) => {
    if (err) return next(err);
    if (!user) {
      // We make our extra check here:
      if (info.message === 'No auth token') return next();
      return res.redirect(...);
    }
    req.login(...);
  })(req, res, next)
}, ...);
```

Though in your case it sounds like you can just do something like this (unless I'm misunderstanding):

```js
router.get('/', (req, res, next) => {
  if (!req.user) {
    return passport.authenticate('jwt', { session: false })(req, res, next);
  }
  next();
}, ...);
```

Also, [you can pass an array of strategy names to `authenticate`](https://github.com/jaredhanson/passport/blob/v0.3.2/lib/middleware/authenticate.js#L66):

> The first strategy to succeed, redirect, or error will halt
> the chain.  Authentication failures will proceed through each strategy in
> series, ultimately failing if all strategies fail.

Though it might be too limiting for your use case.

**Comment by themikenicholson** [comment]
@woutr did @noinkling cover everything.  It looks like this should work without this issue and the related PR.

**Comment by themikenicholson** [comment]
Another thought: If you need a special behavior in the case that a request is not authenticated why not create a custom "No auth" strategy put it last in the list of strategies passed to `authenticate` and make it do whatever custom behavior you want?  Since it would be last in the list you would be ensured it was only handling unauthenticated requests.

**Comment by themikenicholson** [comment]
Closing as it sounds like this is either covered by previous comments or author is no longer interested.
