### ISSUE TITLE
fromHeader + JWT SCHEMA

### ISSUE THREAD

**Issue by rusmichal** [themikenicholson/passport-jwt#99]
Is it possible to add this method? This is the same as `fromHeader` but with JWT schema

function fromCustomHeader(custom_header) {
    return function (request) {

        var token = null;
        if (request.headers[custom_header]) {
            var auth_params = auth_hdr.parse(request.headers[custom_header]);
            if (auth_params && 'JWT' === auth_params.scheme) {
                token = auth_params.value;
            }
        }
        return token;
    };
};

**Comment by themikenicholson** [comment]
I'd prefer not to add new extractor types for every individual use case.  The purpose of the extractor function was to abstract away the details of pulling the JWT out of the request.  

I don't plan to change the extractor API anytime soon and the existing extractors should at least cover the 80% use case.  In this instance I think using your own custom extractor is the best approach
